### ISSUE TITLE
Displaying wrong theme ID

### ISSUE THREAD

**Issue by stankostadinov** [jgodson/shopify-tools#2]
### Problem 

I'm getting wrong theme IDs displayed on my dev store but I haven't spent more time looking at why this is happening.

#### Screenshot
![https://screenshot.click/15-16-rpvx1-4b04b.jpg](https://screenshot.click/15-16-rpvx1-4b04b.jpg)

**Comment by jgodson** [comment]
Ah yes, I think I might know why this is happening. Thanks for submitting an issue! I'll work on a fix for the next release.
